name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:

      fail-fast: false
      
      matrix:
        os: [ubuntu-latest, windows-latest]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: cmake -S ${{ github.workspace }} --preset=release

    - name: Build
      run: cmake --build --preset=release-build
